blank_issues_enabled: false
contact_links:
  - name: ⚠️ Application issue
    url: https://github.com/tachiyomiorg/tachiyomi/issues/new/choose
    about: Issues and requests about the app itself should be opened in the tachiyomi repository instead
  - name: ⚠️ Extension/source issue
    url: https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose
    about: Issues and requests for extensions and sources should be opened in the tachiyomi-extensions repository instead
  - name: 🖥️ Tachiyomi website
    url: https://tachiyomi.org/help/
    about: Guides, troubleshooting, and answers to common questions
